### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by ythecombinator** [temando/open-api-renderer#192]
Hey, thanks for the amazing component!

I've been making a few experiments with it and I ended up facing the following:

```sh
self is not defined
ReferenceError: self is not defined
    at Object.<anonymous> (/Users/mabrasil/Documents/Github/beakyn/docs/final2/node_modules/react-lincoln/Lincoln.js:19:58659)
    at t (/Users/mabrasil/Documents/Github/beakyn/docs/final2/node_modules/react-lincoln/Lincoln.js:1:177)
    at Object.module.exports.Object.defineProperty.value (/Users/mabrasil/Documents/Github/beakyn/docs/final2/node_modules/react-lincoln/Lincoln.js:19:173470)
    at t (/Users/mabrasil/Documents/Github/beakyn/docs/final2/node_modules/react-lincoln/Lincoln.js:1:177)
    at Object.module.exports.Object.defineProperty.value (/Users/mabrasil/Documents/Github/beakyn/docs/final2/node_modules/react-lincoln/Lincoln.js:19:166713)
    at t (/Users/mabrasil/Documents/Github/beakyn/docs/final2/node_modules/react-lincoln/Lincoln.js:1:177)
    at Object.module.exports.Object.defineProperty.value (/Users/mabrasil/Documents/Github/beakyn/docs/final2/node_modules/react-lincoln/Lincoln.js:19:101177)
    at t (/Users/mabrasil/Documents/Github/beakyn/docs/final2/node_modules/react-lincoln/Lincoln.js:1:177)
    at Object.<anonymous> (/Users/mabrasil/Documents/Github/beakyn/docs/final2/node_modules/react-lincoln/Lincoln.js:49:115114)
    at t (/Users/mabrasil/Documents/Github/beakyn/docs/final2/node_modules/react-lincoln/Lincoln.js:1:177)
```

There're many [other](https://github.com/markdalgleish/static-site-generator-webpack-plugin/issues/79) [related](https://github.com/webpack-contrib/style-loader/issues/177) [issues](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/453) out there and it seems to be a problem with `webpack`–and not with `Lincoln` itself–but none of the solutions seemed to be related.

[One of the comments](https://github.com/webpack-contrib/style-loader/issues/177#issuecomment-283805278) got my attention:

> The problem here is that global.self is only defined in Browsers and Web Workers. Unit tests running in NodeJs environment won't have access to global.self.

I think this can be kind of a clue, since I'm doing server-side rendering with [next.js](https://github.com/zeit/next.js) but I still can't figure it out.

Any thoughts?

**Comment by nfour** [comment]
While it would be not-ideal, assembling a `jsdom` environment inside your server-side rendering *could* fix it.

The line in question:
`self.fetch.bind`

So it's trying to reference `fetch` from a global and failing in nodejs. Definitely sounds like a webpack problem or perhaps babel.

**Comment by brendo** [comment]
Looks like this could be semi-related too, https://github.com/matthew-andrews/isomorphic-fetch/issues/125

**Comment by brendo** [comment]
Yo @ythecombinator, I think we might have a fix, did you want to try the above PR?

**Comment by ythecombinator** [comment]
Gonna check this later @nfour and @brendo. Thanks for the fast feedback 😄
